# Generated by Django 5.2.5 on 2025-08-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clienteplano',
            name='status_vencimento',
            field=models.CharField(choices=[('atrasado', 'Atrasado'), ('em dia', 'Em dia')], max_length=20),
        ),
    ]
