# Generated by Django 5.2.5 on 2025-09-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_cliente_sexo_cliente_logradouro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('dias', models.ManyToManyField(related_name='servicos', to='gym.diasemana')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.plano')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.servico')),
            ],
        ),
    ]
