# Generated by Django 5.2.5 on 2025-09-09 19:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_diasemana_servico_planoservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outros', 'Outros')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tipoplano',
            name='dias',
            field=models.IntegerField(default=30, help_text='Número de dias que o plano é válido', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='clienteplano',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('outro', 'Outro')], help_text='Selecione o método de pagamento', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoplano',
            name='nome',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('anual', 'Anual'), ('outros', 'Outros')], default='mensal', max_length=50),
        ),
    ]
