# Generated by Django 5.2.5 on 2025-09-12 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_cliente_sexo_tipoplano_dias_alter_cliente_idade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='logradouro',
            new_name='endereco',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
