# Generated by Django 5.2.5 on 2025-10-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_rename_logradouro_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='planos', through='gym.PlanoServico', to='gym.servico'),
        ),
        migrations.AddField(
            model_name='plano',
            name='tipo_duracao',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('outro', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='dias',
            field=models.ManyToManyField(blank=True, related_name='servicos', to='gym.diasemana'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
