# Generated by Django 5.2.5 on 2025-10-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_plano_servicos_plano_tipo_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='dias_por_semana',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=3, help_text='Número de dias por semana (1-7)'),
        ),
    ]
