# Generated by Django 5.2.5 on 2025-11-20 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_plano_dias_por_semana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistencia',
            new_name='Presenca',
        ),
        migrations.AlterModelOptions(
            name='presenca',
            options={'ordering': ['-data', '-hora'], 'verbose_name': 'Presença', 'verbose_name_plural': 'Presenças'},
        ),
    ]
