# Generated by Django 5.2.5 on 2025-11-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_rename_assistencia_presenca_alter_presenca_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasemana',
            options={'verbose_name': 'Dia da Semana', 'verbose_name_plural': 'Dias da Semana'},
        ),
        migrations.AlterField(
            model_name='diasemana',
            name='nome',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, unique=True),
        ),
    ]
